name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portfolio:alpha-0.1

    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag portfolio:alpha-0.1 ${{ secrets.DOCKER_USERNAME }}/portfolio:alpha-0.1
        docker push ${{ secrets.DOCKER_USERNAME }}/portfolio:alpha-0.1

    - name: Create container and extract files
      run: |
        mkdir -p ./dist
        docker create --name extract portfolio:alpha-0.1
        docker cp extract:/usr/share/nginx/html ./dist
        docker rm -f extract
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/html
